architecture: standalone
global:
  redis:
    password: "redis"
replica:
  replicaCount: 1
master:
  kind: Deployment
image:
  registry: cgr.dev
  repository: cgr-demo.com/redis-server-bitnami
  tag: 7.4.2-r0-202503181613
